
input_img_dim:
  [256,256]
transformer_emb_dim:
  256
transformer_num_heads:
  8
transformer_num_encoder_layer:
  6
transformer_num_dec_layer:
  6
transformer_intermediate_layer_dim:
  512
transformer_dropout_per:
  0.
prior_posterior_layers:
  [64,128,256]
pp_cnn_per_block:
  3
latent_dim:
  256
batch_size:
  64
num_samples:
  16
momentum:
  0.0001
epochs:
  100
learning_rate:
  0.001
data_path:
  "../datasets/augmented_cityscapes"
run_name:
  "cityscapes_higher_lr"
project_name:
  "variational_transformer"
device:
  "cpu"
continue_tra:
  False
wandb_id:
  "test"
